name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Poetry
        run: pip install poetry
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - run: poetry lock
      - run: poetry install
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_ACCESS_TOKEN }}"
      - name: Publish package
        run: poetry publish --build
